name: ci

on:
  push:
    branches:
      - "main"
      
jobs:
  lint:
    name: Lint Go and Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51
          working-directory: src
      - name: Lint Dockerfile
        run: |
          apt-get update
          apt-get install -y hadolint

          hadolint dockerfile
